apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgm-deployment
spec:
  selector:
    matchLabels:
      app: cgm
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
        app: cgm
    spec:
      serviceAccountName: cgm-sa
      containers:
        - name: cgm
          imagePullPolicy: Always
          image: ghcr.io/happymary16/cgm/cgm:latest
          args:
            - cgm-service
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "4"
              memory: "8Gi"
            requests:
              cpu: "2"
              memory: "4Gi"
      imagePullSecrets:
        - name: github-secret
