apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgm-deployment
spec:
  selector:
    matchLabels:
      app: cgm
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
        app: cgm
    spec:
      serviceAccountName: cgm-sa
      containers:
        - name: cgm
          imagePullPolicy: Always
          image: ghcr.io/happymary16/cgm/cgm:latest
          args:
            - cgm-service
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "12Gi"
            requests:
              memory: "8Gi"
          env:
           - name: CGM_FILE_SYSTEM
             value: azure
           - name: CGM_MODE
             value: parallel
      imagePullSecrets:
        - name: github-secret
