apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cgm-ingress
  annotations:
    cert-manager.io/issuer: letsencrypt
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  tls:
    - hosts:
        - "cgm.{{ .Values.cgm.clusterDomain }}"
      secretName: cgm-certificate-secret
  rules:
    - host: "cgm.{{ .Values.cgm.clusterDomain }}"
      http:
        paths:
          - backend:
              service:
                name: cgm-service
                port:
                  number: 80
            path: /
            pathType: Prefix
