name: Terraform Destroy Run

on:
  workflow_dispatch:

concurrency: production

env:
  TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

jobs:
  terraform-apply:
    runs-on: "ubuntu-latest"
    steps:
      - uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.1
        id: create-run-azure
        with:
          workspace: "cgm-azure"
          is_destroy: "true"
      - uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.1
        id: apply-azure
        with:
          run: ${{ steps.create-run-azure.outputs.run_id }}
          comment: "Confirmed from GitHub Actions CI"

      - uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.1
        id: create-run-k8s
        with:
          workspace: "cgm-k8s"
          is_destroy: "true"
      - uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.1
        id: apply-k8s
        with:
          run: ${{ steps.create-run-k8s.outputs.run_id }}
          comment: "Confirmed from GitHub Actions CI"