name: Terraform Destroy Run

on:
  workflow_dispatch:

concurrency: production

env:
  TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
  TF_WORKSPACE: ${{ vars.TF_WORKSPACE }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_DIRECTORY: "."

jobs:
  terraform-apply:
    runs-on: "ubuntu-latest"
    steps:
      - uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.1
        id: create-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          is_destroy: "true"

      - uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.1
        id: apply
        with:
          run: ${{ steps.create-run.outputs.run_id }}
          comment: "Confirmed from GitHub Actions CI"