name: Terraform Apply Run

on:
  workflow_dispatch:

concurrency: production

jobs:
  terraform-cloud-apply-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TF_CLOUD_ORGANIZATION=${{ vars.TF_CLOUD_ORGANIZATION }}"
      - run: echo "TF_WORKSPACE=${{ vars.TF_WORKSPACE }}"
      - run: echo "TF_API_TOKEN is set"
        if: ${{ secrets.TF_API_TOKEN != '' }}
